### ISSUE TITLE
你的富文本编辑器用的什么啊

### ISSUE THREAD

**Issue by ahfoqhgbwekbs** [shuaijunlan/Autumn-Framework#44]
我想了解增删改查

**Comment by shuaijunlan** [comment]
@ahfoqhgbwekbs 你是指Blog那个编辑器么，使用的[editor.md](https://github.com/pandao/editor.md)

**Comment by ahfoqhgbwekbs** [comment]
就是日志添加功能里的文本域,前台接收不到值
